Repository shoc71/Keep-On-Going, pull requests merged in 2023-07, with the labels that each got.

#112 Update updates.txt (v.0.2.5+)
  dont stop now/patch notes/updates.txt
Labels: documentation

#126 dsn_levels v.0.2.6
  dont stop now/dsn_levels.py
Labels: post v.0.2.5

#127 main v.0.1.7
  dont stop now/main.py
Labels: post v.0.2.5

#133 dsn_levels v.0.2.7
  dont stop now/dsn_levels.py
Labels: post v.0.2.5

#135 dsn_levels v.0.2.8
  dont stop now/dsn_levels.py
Labels: post v.0.2.5

#134 dsn_class v.0.2.1
  dont stop now/dsn_class.py
Labels: post v.0.2.5

#152 D-word-file-only
  dont stop now/assets/images/path93.png
Labels: post v.0.2.5

#159 Removing level design image
  dont stop now/assets/images/Screenshot_060823_093646_PM.jpg
Labels: viewed

#161 Level Mouse added to game
  dont stop now/assets/images/Screenshot_060823_093726_PM.jpg
Labels: viewed

#162 deleting and relocation file
  dont stop now/assets/images/Screenshot_060823_093751_PM.jpg
Labels: viewed

#163 deleting and relocating file
  dont stop now/assets/images/Screenshot_060823_093906_PM.jpg
Labels: viewed

#164 level added to game and is now being removed
  dont stop now/assets/images/Screenshot_060823_093918_PM.jpg
Labels: viewed

#166 deleting and relocating file
  dont stop now/assets/images/Screenshot_060823_093947_PM.jpg
Labels: viewed

#167 deleting and relocating file
  dont stop now/assets/images/Screenshot_060823_094002_PM.jpg
Labels: viewed

#168 deleting and relocating file
  dont stop now/assets/images/Screenshot_060823_094017_PM.jpg
Labels: viewed

#171 deleting and relocating file
  dont stop now/assets/images/Screenshot_060823_094224_PM.jpg
Labels: viewed

#172 deleting and relocating file
  dont stop now/assets/images/Screenshot_060823_095020_PM.jpg
Labels: viewed

#175 deleting and relocating file
  dont stop now/assets/images/into the jaws.PNG
Labels: viewed

#178 deleting and relocating file
  dont stop now/assets/images/lvl-design-003.png
Labels: viewed

#179 deleting and relocating file
  dont stop now/assets/images/lvl-design-004.png
Labels: viewed

#180 deleting and relocating file
  dont stop now/assets/images/lvl-design-005.png
Labels: viewed

#181 File has been added and renamed
  dont stop now/assets/images/path93.png
Labels: viewed

#176 level added, now being removed
  dont stop now/assets/images/lvl-design-001.png
Labels: viewed
